services:
  - type: web
    name: banking-chatbot
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    # No need to specify startCommand as it's defined in the Dockerfile
    envVars:
      - key: PORT
        value: 5005