services:
  - type: web
    name: banking-chatbot
    env: docker
    plan: free
    # Explicitly set the start command
    startCommand: rasa run --enable-api --cors "*" --port $PORT
    envVars:
      - key: PORT
        value: 5005