services:
  - type: web
    name: banking-chatbot
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 5005
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          type: web
          name: banking-chatbot
          property: host
    healthCheckPath: /